workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

stages:
  - build
  - test

build:
  stage: build
  tags:
    - bas2302
    - linux
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - chmod +x mvnw
    - ./mvnw -B clean verify
  artifacts:
    paths:
      - target/*.jar
    when: on_success

semgrep-sast:
  stage: test
  tags:
    - bas2302
    - linux
  image: semgrep/semgrep:latest
  needs:
    - build
  script:
    - semgrep scan --config auto --gitlab-sast --output gl-sast-report.json "${CI_PROJECT_DIR}"
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    when: always

dependency-check:
  stage: test
  tags:
    - bas2302
    - linux
  image: maven:3.9.6-eclipse-temurin-21
  needs:
    - build
  script:
    - chmod +x mvnw
    - ./mvnw -B dependency-check:check
  artifacts:
    paths:
      - target/dependency-check-report.html
    when: always